spring:
    thymeleaf:
        prefix: classpath:/templates/
        servlet:
            content-type: text/html
        suffix: .html
        cache: true
        mode: HTML
        encoding: UTF-8
server:
    port: 8081